GET http://127.0.0.1:8000/apartmentsViewSet/ HTTP/1.1
Content-Type: application/json

###


POST  http://127.0.0.1:8000/apartmentsViewSet/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMDA0MjE1LCJpYXQiOjE3NzEwMDM5MTUsImp0aSI6IjhjNmIzMTNiMDhhZjQ2MTlhNWMyZjc3ODEyMGE2NjhjIiwidXNlcl9pZCI6IjEifQ.6HXX95-8XC9HWQIOG8OvHSEZjM4sVfXzimP4vovWI6A

{
    "title": "Apart5",
    "description": "Apart5",
    "city": "Wrocław",
    "price": "5600.00",
    "rooms": 4,
    "area": "67.00",
    "build": "2026-02-10",
    "published": "2026-02-10",
    "pets": true
}

###
POST  http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "kuba",
    "password": "Zcadqe13"
 
}